# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'map Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for map Demo

  target 'map DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'map DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'GoogleMaps'


end
